### ISSUE TITLE
Remove Hard Coding from Status Reconciler

### ISSUE THREAD

**Issue by acornett21** [opdev/docling-operator#22]
Currently the status reconciler has hard-coded values inplace for the `GET` calls. We should look into using label selectors, or some other dynamic means in our `GET` calls. This would ensure that no matter the CR name, the status would get updated and not error. 

Example below which shows the mismatch:

```yaml
conditions:
  - lastTransitionTime: "2025-04-07T15:27:42Z"
    message: Deployment.apps "docling-serv" not found
    reason: DeploymentStatusError
    status: Unknown
    type: DeploymentCreated
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-04-07T15:27:42Z"
  generation: 1
  name: doclingserv-sample-deployment
  namespace: docling
```
