### ISSUE TITLE
Allow a persistence volume for model weights

### ISSUE THREAD

**Issue by dolfim-ibm** [opdev/docling-operator#47]
## Problem description

Docling requires AI models for converting the documents. Which models is only known at runtime and it might be different for each API request.
In Docling Serve we took the approach of storing the model common model weights in the container image, but this creates issues with users who request the features provided by the extra models.

## Proposed solution

To allow users to download all the required models, and to keep them "cached" in the cluster, we suggest adding the optional possibility to:
 
1. add a persistent volume to the deployment
2. add an `initContainers` which downloads the requested models in the volume

For completeness, we could give the users 3 choices:
- Option 1: No volume. Just use what is there by default
- Option 2: Request the operator to provision a pvc and specify which models are requested
- Option 3: Provide pointers to an existing pvc and specify which models are requested

### Proposed specs

```yaml
kind: DoclingServe
spec:
  artifactsVolume:
    enable: false | true  # default false
    models: ""  # a space separated list like"layout tableformer code_formula picture_classifier smolvlm granite_vision easyocr"
    volumeClaimTemplates:  # optional
      - {}  # the specs for a volumeClaim (see below examples)
```

The default pvc settings should request for 16GB storage and `accessMode: ReadWriteMany`.

Inspired by other operators (e.g. [elasticsearch](https://www.elastic.co/docs/deploy-manage/deploy/cloud-on-k8s/volume-claim-templates)) Users could provide the `volumeClaim` details for advanced changes, for example:

- A different size or storage class:

    ```yaml
    volumeClaimTemplates:
      - metadata:
        name: docling-models
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 20Gi
          storageClassName: standard
    ```

- Point to an existing volume:

    ```yaml
    volumeClaimTemplates:
      - metadata:
        name: docling-models
        spec:
          storageClassName: ""
          volumeName: foo-pv    
    ```

### Changes in the Deployment

1. Mount the volume, e.g. in `/opt/docling/models` (just a proposal)
2. Set the ENV `DOCLING_SERVER_ARTIFACTS_PATH=/opt/docling/models` (the actual mount point)
3. Add a `initContainers` using the same image but a different `command`:

    ```yaml
    initContainers:
      - name: docling-models-download
        image: <spec.apiServer.image>
        command: ['sh', '-c', "docling-tools models download -o <mountPoint> <spec.artifactsVolume.models>"]
    ```

**Comment by bcrochet** [comment]
I'd prefer `models` be an actual list. No sense in making it harder to parse.

**Comment by acornett21** [comment]
We probably don't need `enabled` as well, since the presence of  `artifactsVolume` will let us know to do custom things.

> The default pvc settings should request for 16GB storage and accessMode: ReadWriteMany.

@dolfim-ibm Can you explain the above further? Are you saying that the `docling-serve` workload now needs a PVC by default?

**Comment by dolfim-ibm** [comment]
Not really by default. The key is the three options described in the description above.

**Comment by bcrochet** [comment]
> > I'd prefer `models` be an actual list. No sense in making it harder to parse.
> 
> Either is ok with me. Eventually the CLI will need the space-separated list.

That part is easy enough. I'll stick with a list.

**Comment by bcrochet** [comment]
Should `models` actually be a top-level attribute? That would allow us to get rid of the `enabled` attribute. 

1. No `artifactsVolume` specified. This would be the default, and make that part completely optional.

```yaml
kind: DoclingServe
spec:
    models:
        - layout
        - tableformer
        - code_formula
        - picture_classifier
```

2. `artifactsVolume` specified, but no template. This would give a default (16G as stated above) pvc, with accessmodes of ROX and RWO. (As far as I can tell this is allowed?)

```yaml
kind: DoclingServe
spec:
    models:
        - layout
        - tableformer
        - code_formula
        - picture_classifier
    artifactsVolume: {}
```


3. `artifactsVolume` specified, and additional attributes, like size, name, and storage class are specified. These are liktely the only parts of the pvc template that we want to allow. The operator needs to handle the other parts.

```yaml
kind: DoclingServe
spec:
    models:
        - layout
        - tableformer
        - code_formula
        - picture_classifier
    artifactsVolume:
        storage: 16G
        name: modelvol
        storageClassName: mysuperfaststorage
```
